name: loser_night
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_olm: ^2.0.0
  flutter_openssl_crypto: ^0.5.0
  matrix: ^0.29.13
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  flutter_web_auth: ^0.5.0
  flutter_slidable: ^3.0.1
  intl: any
  scroll_to_index: ^3.0.1
  http: ^1.2.1
  chat_bubbles: ^1.6.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
