name: loser_night
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_olm: ^2.0.0
  flutter_openssl_crypto: ^0.5.0
  matrix: ^0.30.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  flutter_web_auth_2: ^4.1.0
  flutter_slidable:
    git:
      url: "https://github.com/letsar/flutter_slidable"
  intl: any
  scroll_to_index: ^3.0.1
  http: ^1.2.1
  hive: ^2.2.3
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  flutter_map_location_picker: ^0.0.4
  permission_handler: ^11.0.1
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  flutter_localizations:
    sdk: flutter
  linagora_design_flutter:
    git:
      url: https://github.com/linagora/linagora-design-flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
